2 fast 2 furious
sociam/xray-archiver pull request #76
Opened 2017-08-21 23:32 UTC by deanott

2017-08-22 15:08 UTC, sauyon requested changes
Please don't remove order by

2017-08-24 08:28 UTC, sauyon submitted a review, later dismissed

2017-09-22 11:12 UTC, AdamSlack commented on pipeline/db/db.go
> +func anyPatternFormat(arr *[]string) {
Equally bad if not worse name

2017-09-22 11:17 UTC, AdamSlack requested changes

2017-09-22 11:17 UTC, AdamSlack commented on pipeline/db/db.go
> +func startsWithPatternFormat(arr *[]string) {
same as above. doesn't indicate what the function does. this name implies that it's checking something and returns a bool

2017-09-22 11:17 UTC, AdamSlack commented on pipeline/db/db.go
> +	var querystr string
Camel case?

2017-09-22 11:26 UTC, AdamSlack requested changes

2017-09-22 11:26 UTC, AdamSlack commented on pipeline/db/db.go
> +func arrRegexAnyFormat(arr *[]string) {
this is essentially the same. implies that this function is checking if something fits in a specific format

2017-09-22 11:26 UTC, AdamSlack commented on pipeline/db/db.go
> +func startsWithRegexFormat(arr *[]string) {
this is essentially the same. implies that this function is checking if something fits in a specific format

2017-09-22 11:34 UTC, AdamSlack submitted a review, later dismissed

2017-09-25 13:03 UTC, AdamSlack approved these changes

2017-09-25 13:47 UTC, merged